### ISSUE TITLE
Can I help ?

### ISSUE THREAD

**Issue by vanwalj** [nicholejeannine/SkuleSite#1]
It seem's that's you now master express and Sequelize :), tell me if I can help you !
I'm pretty stuck trying to figure out why it won't let me access any of the pages you need to be signed in in order to view. I've refactored the whole thing so many times and have been looking at this code for so long I don't even know where things are anymore! :(  I would love to have you take a look if you don't mind and have time. I'm going to have dinner with the group in just a few minutes but I'll check back afterward. Thank you!! :)

**Comment by nicholejeannine** [comment]
Oops I just edited your comment instead of replying .... sorry!

**Comment by nicholejeannine** [comment]
And oops. I just saw the really obvious mistake .... ouch. -1 for me !!

**Comment by vanwalj** [comment]
No more help needed ? :)

**Comment by nicholejeannine** [comment]
I may contact you at some point for questions as they arise .... working on refactoring this now and it's making so much more sense!! :) So exciting!!! :)

**Comment by vanwalj** [comment]
I'd be glad to help you, just let me know if you need help :)
